const conv={en:{q:'What do you usually do on weekends?',a:'I usually go swimming on weekends.',m:'저는 주말에 보통 수영하러 가요.'},ja:{q:'週末は何をしますか？',a:'週末はよく泳ぎに行きます。',m:'주말에는 보통 수영하러 갑니다.'},yue:{q:'你週末通常做咩？',a:'我通常去游水。',m:'저는 주말에 보통 수영하러 가요.'}};
const ys=[['你好','nei5 hou2','네이 호우','안녕하세요'],['唔該','m4 goi1','음고이','감사합니다 / 부탁합니다'],['多謝','do1 ze6','도제','감사합니다'],['唔好意思','m4 hou2 ji3 si1','음 호우 이 시','실례합니다 / 죄송합니다'],['呢個幾錢？','ni1 go3 gei2 cin2','니 고 게이 친','이거 얼마예요?'],['我要呢個。','ngo5 jiu3 ni1 go3','응오 이우 니 고','이거 주세요.'],['有冇英文餐牌？','jau5 mou5 jing1 man4 caan1 paai4','야우 모우 잉 만 찬 파이','영어 메뉴가 있나요?'],['唔該，埋單。','m4 goi1, maai4 daan1','음고이, 마이 단','계산해주세요.'],['洗手間喺邊度？','sai2 sau2 gaan1 hai2 bin1 dou6','사이 사우 간 하이 빈 도우','화장실이 어디예요?'],['地鐵站喺邊度？','dei6 tit3 zaam6 hai2 bin1 dou6','데이 팃 잠 하이 빈 도우','지하철역이 어디예요?'],['我唔明。','ngo5 m4 ming4','응오 음 밍','이해하지 못해요.'],['請講慢啲。','cing2 gong2 maan6 di1','쳉 공 만 디','천천히 말해주세요.'],['好食！','hou2 sik6','호우 식','맛있어요!'],['有冇折？','jau5 mou5 zit3','야우 모우 짓','할인되나요?'],['唔該晒！','m4 goi1 saai3','음고이 사이','정말 감사합니다.']];let lang='en',yi=0;
function $(x){return document.getElementById(x)}function openPage(id,btn){document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));$(id).classList.add('on');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');if(id==='chat')initChat();if(id==='travel')renderYue();if(id==='progress')renderReviews();scrollTo(0,0)}
function startChat(l,b){lang=l;openPage('chat',b);initChat()}function initChat(){$('messages').innerHTML='<div class="msg"><b>AI</b><br>'+conv[lang].q+'<br><button class="outline" onclick="speak(conv[lang].q,\''+(lang==='en'?'en-US':lang==='ja'?'ja-JP':'zh-HK')+'\')">🔊 듣기</button></div>';$('answer').value=''}
function send(){let v=$('answer').value.trim();if(!v){toast('답변을 입력해 주세요.');return}let x=conv[lang],ok=norm(v)===norm(x.a);$('messages').insertAdjacentHTML('beforeend','<div class="msg me">'+safe(v)+'</div>');if(ok){$('messages').insertAdjacentHTML('beforeend','<div class="msg">✅ 아주 좋아요! 자연스럽습니다.<br><small>'+x.m+'</small></div>')}else{$('messages').insertAdjacentHTML('beforeend','<div class="fix"><b>✏️ 교정 예시</b><br>'+x.a+'<br><small>'+x.m+'</small></div>');let r=JSON.parse(localStorage.reviews||'[]');r.unshift({v,c:x.a});localStorage.reviews=JSON.stringify(r.slice(0,20))}$('answer').value='';$('messages').scrollTop=$('messages').scrollHeight}
function norm(s){return s.toLowerCase().replace(/[.,!?。，！？]/g,'').replace(/\s+/g,' ').trim()}function safe(s){return s.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function speak(t,l){if(!('speechSynthesis'in window)){toast('음성 기능을 지원하지 않습니다.');return}let u=new SpeechSynthesisUtterance(t);u.lang=l||'en-US';u.rate=.88;speechSynthesis.cancel();speechSynthesis.speak(u)}
function voice(){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast('Chrome 음성 입력을 사용해 주세요.');return}let r=new R();r.lang=lang==='en'?'en-US':lang==='ja'?'ja-JP':'zh-HK';r.onresult=e=>$('answer').value=e.results[0][0].transcript;r.start();toast('말씀해 주세요…')}
function renderYue(){let x=ys[yi%ys.length];$('day').textContent='DAY '+(yi+1);$('yue').textContent=x[0];$('jyutping').textContent=x[1];$('pron').textContent=x[2];$('meaning').textContent=x[3]}function hearYue(){speak(ys[yi%ys.length][0],'zh-HK')}function nextYue(){yi=(yi+1)%30;renderYue();toast('Day '+(yi+1)+'로 이동했습니다.')}function renderReviews(){let r=JSON.parse(localStorage.reviews||'[]');$('reviews').textContent=r.length;$('reviewList').innerHTML=r.length?r.slice(0,8).map(x=>'<p>❌ '+safe(x.v)+'<br>→ '+safe(x.c)+'</p>').join(''):'아직 없습니다.'}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.remove('show'),2000)}renderYue();renderReviews();
